### ISSUE TITLE
LoginJAIN?

### ISSUE THREAD

**Issue by PhilippSteinke** [whatatoddler/COWLIFE#12]
http://strawpoll.me/5859614

**Comment by MalibuKanada** [comment]
Ist das dann bindend?

**Comment by MalibuKanada** [comment]
Will ich als Spieler denn die Möglichkeit haben den Spielestand abzuspeichern? Möchte ich irgendeine Art Punkte Sammeln, ein Profil haben, und wenn ja warum? Wenn nein, warum nicht?

**Comment by MalibuKanada** [comment]
Weitere Kommentare?

**Comment by whatatoddler** [comment]
Also ich würde die Entscheidung jetzt Philipp überlassen. Nach dem letzten Gespräch mit Alpers ist der Druck bezüglich dem Umfang des mySQL-Teils ja glaube ich etwas genommen, und für den HTML-Teil fallen mir noch genug Sachen ein, die ich einbauen kann. Aber wenn Philipp meint, er brauch noch mehr an dem er arbeiten kann, könnte man das natürlich noch machen.

**Comment by PhilippSteinke** [comment]
erstmal auf hold würde ich sagen. hat ja jeder genug zu tun. wenn sich herausstellt, dass wir noch was machen müssen (bzw mysql noch zu lahm ist) kann man ja nochmal drüber reden

**Comment by MalibuKanada** [comment]
gut dann mach ich mal zu hier :)
