### ISSUE TITLE
Syntaxfehler in den MySQL Queries

### ISSUE THREAD

**Issue by MalibuKanada** [whatatoddler/COWLIFE#20]
In den SQL Queries befinden sich Syntaxfehler. 1. kein abschließendes Semikolon hinter den Queries bitte :)

Hier die Fehlermeldungen bei meinem Testlauf: 

Fehler beim Erzeugen der Tabelle: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' picturelink TEXT, objectid SMALLINT, object2id SMALLINT, object3id ' at line 4

Fehler beim Erzeugen der Tabelle: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'size), picturelink TEXT, eventid SMALLINT(size), name VARCHAR(size), ' at line 3

Fehler beim Erzeugen der Tabelle: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'size), NAME VARCHAR(size), CODE MEDIUMTEXT, UNIQUE(id, name), PRIMAR' at line 3

Fehler bei mindestens einer Tabelle

**Comment by PhilippSteinke** [comment]
pull request mit neuen queries

**Comment by MarvinGo** [comment]
in pull request #26
