### ISSUE TITLE
Canvas leer wenn Buttons gelöscht

### ISSUE THREAD

**Issue by whatatoddler** [whatatoddler/COWLIFE#23]
Habe die Buttons jetzt nur per CSS versteckt. Wenn ich die Buttons komplett aus der index.html entferne, bleibt merkwürdigerweise das Canvas leer.
Hat das was mit deinem JS Code zu tun?

**Comment by MalibuKanada** [comment]
ja sieht so aus. das JS versucht vermutlich auf das Element zuzugreifen und ist dann beleidigt, weils einfach nicht mehr da ist.

**Comment by MalibuKanada** [comment]
in #24 gelöst, schließe hier
