### ISSUE TITLE
SQL Queries für das Install Script

### ISSUE THREAD

**Issue by MalibuKanada** [whatatoddler/COWLIFE#3]
Für ein Installscript, welches die notwendigen MYSQL Tables erstellt bräuchte ich die kompletten SQL Queries für's Erstellen der Tables. Gerne in einer txt Datei.

Danke

**Comment by PhilippSteinke** [comment]
//das passt noch nicht ganz. (PRIMARY, UNIQUE) fehlt und die Verbindung zwischen scenes & objects

CREATE DATABASE cowlife;

---

CREATE TABLE scenes
(
id SMALLINT(size),
name VARCHAR(size),
link TEXT,
objectid SMALLINT(size),
position SMALLINT
);

---

CREATE TABLE objects
(
id SMALLINT(size),
link TEXT,
eventid SMALLINT(size),
name VARCHAR(size),
position SMALLINT
);

---

CREATE TABLE events
(
ID SMALLINT(size),
NAME VARCHAR(size),
CODE MEDIUMTEXT,
);

**Comment by PhilippSteinke** [comment]
siehe "neuer Ordner"

**Comment by MalibuKanada** [comment]
Du bist ja sehr zuversichtlich, wenn du hier gleich dicht machst ;)

**Comment by MalibuKanada** [comment]
aber danke :)
