### ISSUE TITLE
HTML Frontend für das Installscript

### ISSUE THREAD

**Issue by MalibuKanada** [whatatoddler/COWLIFE#4]
Brauchen ein HTML Formular, mit welchem der Benutzer (also wir) per Knopfdruck alle SQL Tabellen kann. 

Attribute:
<form action="createtables.php" method="POST">
<button type="submit">

**Comment by MalibuKanada** [comment]
das Form Element bitte mit action="createtables.php" method="post"
und ein <input type="submit" />

**Comment by whatatoddler** [comment]
Bitte mal bewerten, ob und was beim installscript.html noch fehlt.

**Comment by MalibuKanada** [comment]
geht klar, Zeile 8 erschließt sich mir nicht. Gerne nen Pull Request öffnen, da kann mans wunderbar prüfen alles, sollten noch noindex Meta Data und so was rein.

**Comment by MalibuKanada** [comment]
Wenn der Pull Rewuest offen ist kann man das durch weiteres commiten/pushen da noch aktualisieren, bis es passt.

**Comment by MalibuKanada** [comment]
mache hier mal zu
